<?php

/**
 * Created by PhpStorm.
 * User: coolong
 * Date: 2017/4/8
 * Time: 10:32
 */
namespace app\bind\controller;
use app\common\controller\Common;
use app\common\tool\location\BaiduMap;
use think\Config;

class Index extends Common
{
    protected $db;
    public function __construct()
    {
        parent::__construct();
        $this->db = model('card/CarCard');
    }

    public function bind($info,$id=0)
    {
        //验证手机验证码
        $m_verify_code = model('notice/VerifyCode');
        $m_verify_code->startTrans();
        try{
            if(!$m_verify_code->check_code($info['phone'],$info['code'])){
                return $m_verify_code->getError();
            }
            if($id){       //二维码id
                $info['id'] = $id;
            }
            unset($info['code']);
            $info['uid'] = $this->user['id'];
            $result = $this->db->bindCard($info);
            if($result){
                $m_verify_code->commit();
                return ['errCode'=>0,'errMsg'=>'绑定成功'];
            }else{
                $m_verify_code->rollback();
                $error = $this->db->getError();
                return ['errCode'=>1,'errMsg'=>$error?:'操作异常'];
            }
        }catch (Exception $e) {
            $m_verify_code->rollback();
        }


    }

    /**
     * 获取地理位置
     */
    public function get_location()
    {
        $lat = input('lat');
        $lng = input('lng');
        $map = new BaiduMap();
        $result = $map->province($lat.",".$lng,3);
        if($result){
            $province = Config::get('location.PROVINCE');
            return [
                'location'=>(int)$province[$result]['id'],  //获取的地理位置id
                'data'=>array_values($province),            //所有省份信息
                'name'=>array_column($province,'name')      //所有省份名称
            ];
        }else{
            return $map->getError();
        }

    }

    public function test()
    {
        $a = "{
\"result\":[
		{
			\"provinceId\":\"11\",
			\"cityId\":\"11\",
			\"cityName\":\"北京\",
			\"fixName\":\"京A\",
			\"frameLength\":\"0\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"北京市\"
		},
		{
			\"provinceId\":\"11\",
			\"cityId\":\"11\",
			\"cityName\":\"北京出租\",
			\"fixName\":\"京B\",
			\"frameLength\":\"0\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"北京市\"
		},
		{
			\"provinceId\":\"11\",
			\"cityId\":\"11\",
			\"cityName\":\"北京\",
			\"fixName\":\"京C\",
			\"frameLength\":\"0\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"北京市\"
		},
		{
			\"provinceId\":\"11\",
			\"cityId\":\"11\",
			\"cityName\":\"北京\",
			\"fixName\":\"京E\",
			\"frameLength\":\"0\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"北京市\"
		},
		{
			\"provinceId\":\"11\",
			\"cityId\":\"11\",
			\"cityName\":\"北京市(城区)\",
			\"fixName\":\"京F\",
			\"frameLength\":\"0\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"北京市\"
		},
		{
			\"provinceId\":\"11\",
			\"cityId\":\"11\",
			\"cityName\":\"北京市(远郊区)\",
			\"fixName\":\"京G\",
			\"frameLength\":\"0\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"北京市\"
		},
		{
			\"provinceId\":\"11\",
			\"cityId\":\"11\",
			\"cityName\":\"北京(警察)\",
			\"fixName\":\"京O\",
			\"frameLength\":\"0\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"北京市\"
		},
		{
			\"provinceId\":\"11\",
			\"cityId\":\"11\",
			\"cityName\":\"北京\",
			\"fixName\":\"京Q\",
			\"frameLength\":\"0\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"北京市\"
		},
		{
			\"provinceId\":\"12\",
			\"cityId\":\"12\",
			\"cityName\":\"天津\",
			\"fixName\":\"津A\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"天津市\"
		},
		{
			\"provinceId\":\"13\",
			\"cityId\":\"1301\",
			\"cityName\":\"石家庄\",
			\"fixName\":\"冀A\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"河北省\"
		},
		{
			\"provinceId\":\"13\",
			\"cityId\":\"1302\",
			\"cityName\":\"唐山\",
			\"fixName\":\"冀B\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"河北省\"
		},
		{
			\"provinceId\":\"13\",
			\"cityId\":\"1303\",
			\"cityName\":\"秦皇岛\",
			\"fixName\":\"冀C\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"河北省\"
		},
		{
			\"provinceId\":\"13\",
			\"cityId\":\"1304\",
			\"cityName\":\"邯郸\",
			\"fixName\":\"冀D\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"河北省\"
		},
		{
			\"provinceId\":\"13\",
			\"cityId\":\"1305\",
			\"cityName\":\"邢台\",
			\"fixName\":\"冀E\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"河北省\"
		},
		{
			\"provinceId\":\"13\",
			\"cityId\":\"1306\",
			\"cityName\":\"保定\",
			\"fixName\":\"冀F\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"河北省\"
		},
		{
			\"provinceId\":\"13\",
			\"cityId\":\"1307\",
			\"cityName\":\"张家口\",
			\"fixName\":\"冀G\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"河北省\"
		},
		{
			\"provinceId\":\"13\",
			\"cityId\":\"1308\",
			\"cityName\":\"承德\",
			\"fixName\":\"冀H\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"河北省\"
		},
		{
			\"provinceId\":\"13\",
			\"cityId\":\"1309\",
			\"cityName\":\"沧州\",
			\"fixName\":\"冀J\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"河北省\"
		},
		{
			\"provinceId\":\"13\",
			\"cityId\":\"1310\",
			\"cityName\":\"廊坊\",
			\"fixName\":\"冀R\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"河北省\"
		},
		{
			\"provinceId\":\"13\",
			\"cityId\":\"1311\",
			\"cityName\":\"衡水\",
			\"fixName\":\"冀T\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"河北省\"
		},
		{
			\"provinceId\":\"13\",
			\"cityId\":\"1312\",
			\"cityName\":\"沧州行署\",
			\"fixName\":\"冀S\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"河北省\"
		},
		{
			\"provinceId\":\"14\",
			\"cityId\":\"1401\",
			\"cityName\":\"太原\",
			\"fixName\":\"晋A\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山西省\"
		},
		{
			\"provinceId\":\"14\",
			\"cityId\":\"1402\",
			\"cityName\":\"大同\",
			\"fixName\":\"晋B\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山西省\"
		},
		{
			\"provinceId\":\"14\",
			\"cityId\":\"1403\",
			\"cityName\":\"阳泉\",
			\"fixName\":\"晋C\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山西省\"
		},
		{
			\"provinceId\":\"14\",
			\"cityId\":\"1404\",
			\"cityName\":\"长治\",
			\"fixName\":\"晋D\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山西省\"
		},
		{
			\"provinceId\":\"14\",
			\"cityId\":\"1405\",
			\"cityName\":\"晋城\",
			\"fixName\":\"晋E\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山西省\"
		},
		{
			\"provinceId\":\"14\",
			\"cityId\":\"1406\",
			\"cityName\":\"朔州\",
			\"fixName\":\"晋F\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山西省\"
		},
		{
			\"provinceId\":\"14\",
			\"cityId\":\"1407\",
			\"cityName\":\"晋中\",
			\"fixName\":\"晋K\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山西省\"
		},
		{
			\"provinceId\":\"14\",
			\"cityId\":\"1408\",
			\"cityName\":\"运城\",
			\"fixName\":\"晋M\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山西省\"
		},
		{
			\"provinceId\":\"14\",
			\"cityId\":\"1409\",
			\"cityName\":\"忻州\",
			\"fixName\":\"晋H\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山西省\"
		},
		{
			\"provinceId\":\"14\",
			\"cityId\":\"1410\",
			\"cityName\":\"临汾\",
			\"fixName\":\"晋L\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山西省\"
		},
		{
			\"provinceId\":\"14\",
			\"cityId\":\"1411\",
			\"cityName\":\"吕梁\",
			\"fixName\":\"晋J\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山西省\"
		},
		{
			\"provinceId\":\"14\",
			\"cityId\":\"1423\",
			\"cityName\":\"雁北\",
			\"fixName\":\"晋G\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山西省\"
		},
		{
			\"provinceId\":\"15\",
			\"cityId\":\"1501\",
			\"cityName\":\"呼和浩特\",
			\"fixName\":\"蒙A\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"内蒙古\"
		},
		{
			\"provinceId\":\"15\",
			\"cityId\":\"1502\",
			\"cityName\":\"包头\",
			\"fixName\":\"蒙B\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"内蒙古\"
		},
		{
			\"provinceId\":\"15\",
			\"cityId\":\"1503\",
			\"cityName\":\"乌海\",
			\"fixName\":\"蒙C\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"内蒙古\"
		},
		{
			\"provinceId\":\"15\",
			\"cityId\":\"1504\",
			\"cityName\":\"赤峰\",
			\"fixName\":\"蒙D\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"内蒙古\"
		},
		{
			\"provinceId\":\"15\",
			\"cityId\":\"1505\",
			\"cityName\":\"通辽\",
			\"fixName\":\"蒙G\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"内蒙古\"
		},
		{
			\"provinceId\":\"15\",
			\"cityId\":\"1506\",
			\"cityName\":\"鄂尔多斯\",
			\"fixName\":\"蒙K\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"内蒙古\"
		},
		{
			\"provinceId\":\"15\",
			\"cityId\":\"1507\",
			\"cityName\":\"呼伦贝尔盟\",
			\"fixName\":\"蒙E\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"内蒙古\"
		},
		{
			\"provinceId\":\"15\",
			\"cityId\":\"1508\",
			\"cityName\":\"巴彦淖尔盟\",
			\"fixName\":\"蒙L\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"内蒙古\"
		},
		{
			\"provinceId\":\"15\",
			\"cityId\":\"1509\",
			\"cityName\":\"乌兰察布盟\",
			\"fixName\":\"蒙J\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"内蒙古\"
		},
		{
			\"provinceId\":\"15\",
			\"cityId\":\"1522\",
			\"cityName\":\"兴安盟\",
			\"fixName\":\"蒙F\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"内蒙古\"
		},
		{
			\"provinceId\":\"15\",
			\"cityId\":\"1525\",
			\"cityName\":\"锡林郭勒盟\",
			\"fixName\":\"蒙H\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"内蒙古\"
		},
		{
			\"provinceId\":\"15\",
			\"cityId\":\"1529\",
			\"cityName\":\"阿拉善盟\",
			\"fixName\":\"蒙M\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"内蒙古\"
		},
		{
			\"provinceId\":\"21\",
			\"cityId\":\"2101\",
			\"cityName\":\"沈阳\",
			\"fixName\":\"辽A\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"辽宁省\"
		},
		{
			\"provinceId\":\"21\",
			\"cityId\":\"2102\",
			\"cityName\":\"大连\",
			\"fixName\":\"辽B\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"辽宁省\"
		},
		{
			\"provinceId\":\"21\",
			\"cityId\":\"2103\",
			\"cityName\":\"鞍山\",
			\"fixName\":\"辽C\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":false,
			\"provinceName\":\"辽宁省\"
		},
		{
			\"provinceId\":\"21\",
			\"cityId\":\"2104\",
			\"cityName\":\"抚顺\",
			\"fixName\":\"辽D\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"辽宁省\"
		},
		{
			\"provinceId\":\"21\",
			\"cityId\":\"2105\",
			\"cityName\":\"本溪\",
			\"fixName\":\"辽E\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"辽宁省\"
		},
		{
			\"provinceId\":\"21\",
			\"cityId\":\"2106\",
			\"cityName\":\"丹东\",
			\"fixName\":\"辽F\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"辽宁省\"
		},
		{
			\"provinceId\":\"21\",
			\"cityId\":\"2107\",
			\"cityName\":\"锦州\",
			\"fixName\":\"辽G\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"辽宁省\"
		},
		{
			\"provinceId\":\"21\",
			\"cityId\":\"2108\",
			\"cityName\":\"营口\",
			\"fixName\":\"辽H\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"辽宁省\"
		},
		{
			\"provinceId\":\"21\",
			\"cityId\":\"2109\",
			\"cityName\":\"阜新\",
			\"fixName\":\"辽J\",
			\"frameLength\":\"6\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"辽宁省\"
		},
		{
			\"provinceId\":\"21\",
			\"cityId\":\"2110\",
			\"cityName\":\"辽阳\",
			\"fixName\":\"辽K\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"辽宁省\"
		},
		{
			\"provinceId\":\"21\",
			\"cityId\":\"2111\",
			\"cityName\":\"盘锦\",
			\"fixName\":\"辽L\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"辽宁省\"
		},
		{
			\"provinceId\":\"21\",
			\"cityId\":\"2112\",
			\"cityName\":\"铁岭\",
			\"fixName\":\"辽M\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"辽宁省\"
		},
		{
			\"provinceId\":\"21\",
			\"cityId\":\"2113\",
			\"cityName\":\"朝阳\",
			\"fixName\":\"辽N\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"辽宁省\"
		},
		{
			\"provinceId\":\"21\",
			\"cityId\":\"2114\",
			\"cityName\":\"葫芦岛\",
			\"fixName\":\"辽P\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"辽宁省\"
		},
		{
			\"provinceId\":\"22\",
			\"cityId\":\"2201\",
			\"cityName\":\"长春\",
			\"fixName\":\"吉A\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"吉林省\"
		},
		{
			\"provinceId\":\"22\",
			\"cityId\":\"2202\",
			\"cityName\":\"吉林\",
			\"fixName\":\"吉B\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"吉林省\"
		},
		{
			\"provinceId\":\"22\",
			\"cityId\":\"2203\",
			\"cityName\":\"四平\",
			\"fixName\":\"吉C\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"吉林省\"
		},
		{
			\"provinceId\":\"22\",
			\"cityId\":\"2204\",
			\"cityName\":\"辽源\",
			\"fixName\":\"吉D\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"吉林省\"
		},
		{
			\"provinceId\":\"22\",
			\"cityId\":\"2205\",
			\"cityName\":\"通化\",
			\"fixName\":\"吉E\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"吉林省\"
		},
		{
			\"provinceId\":\"22\",
			\"cityId\":\"2206\",
			\"cityName\":\"白山\",
			\"fixName\":\"吉F\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"吉林省\"
		},
		{
			\"provinceId\":\"22\",
			\"cityId\":\"2207\",
			\"cityName\":\"松原\",
			\"fixName\":\"吉J\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"吉林省\"
		},
		{
			\"provinceId\":\"22\",
			\"cityId\":\"2208\",
			\"cityName\":\"白城\",
			\"fixName\":\"吉G\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"吉林省\"
		},
		{
			\"provinceId\":\"22\",
			\"cityId\":\"2224\",
			\"cityName\":\"延边朝鲜族自治州\",
			\"fixName\":\"吉H\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"吉林省\"
		},
		{
			\"provinceId\":\"23\",
			\"cityId\":\"2301\",
			\"cityName\":\"哈尔滨\",
			\"fixName\":\"黑A\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"黑龙江\"
		},
		{
			\"provinceId\":\"23\",
			\"cityId\":\"2302\",
			\"cityName\":\"齐齐哈尔\",
			\"fixName\":\"黑B\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"黑龙江\"
		},
		{
			\"provinceId\":\"23\",
			\"cityId\":\"2303\",
			\"cityName\":\"鸡西\",
			\"fixName\":\"黑G\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"黑龙江\"
		},
		{
			\"provinceId\":\"23\",
			\"cityId\":\"2304\",
			\"cityName\":\"鹤岗\",
			\"fixName\":\"黑H\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"黑龙江\"
		},
		{
			\"provinceId\":\"23\",
			\"cityId\":\"2305\",
			\"cityName\":\"双鸭山\",
			\"fixName\":\"黑J\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"黑龙江\"
		},
		{
			\"provinceId\":\"23\",
			\"cityId\":\"2306\",
			\"cityName\":\"大庆\",
			\"fixName\":\"黑E\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"黑龙江\"
		},
		{
			\"provinceId\":\"23\",
			\"cityId\":\"2307\",
			\"cityName\":\"伊春\",
			\"fixName\":\"黑F\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"黑龙江\"
		},
		{
			\"provinceId\":\"23\",
			\"cityId\":\"2308\",
			\"cityName\":\"佳木斯\",
			\"fixName\":\"黑D\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"黑龙江\"
		},
		{
			\"provinceId\":\"23\",
			\"cityId\":\"2309\",
			\"cityName\":\"七台河\",
			\"fixName\":\"黑K\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"黑龙江\"
		},
		{
			\"provinceId\":\"23\",
			\"cityId\":\"2310\",
			\"cityName\":\"牡丹江\",
			\"fixName\":\"黑C\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"黑龙江\"
		},
		{
			\"provinceId\":\"23\",
			\"cityId\":\"2311\",
			\"cityName\":\"黑河\",
			\"fixName\":\"黑N\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"黑龙江\"
		},
		{
			\"provinceId\":\"23\",
			\"cityId\":\"2312\",
			\"cityName\":\"绥化\",
			\"fixName\":\"黑M\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"黑龙江\"
		},
		{
			\"provinceId\":\"23\",
			\"cityId\":\"2327\",
			\"cityName\":\"大兴安岭\",
			\"fixName\":\"黑P\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"黑龙江\"
		},
		{
			\"provinceId\":\"23\",
			\"cityId\":\"2328\",
			\"cityName\":\"松花江\",
			\"fixName\":\"黑L\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"黑龙江\"
		},
		{
			\"provinceId\":\"23\",
			\"cityId\":\"2329\",
			\"cityName\":\"农垦系统\",
			\"fixName\":\"黑R\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"黑龙江\"
		},
		{
			\"provinceId\":\"31\",
			\"cityId\":\"31\",
			\"cityName\":\"上海\",
			\"fixName\":\"沪A\",
			\"frameLength\":\"0\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"上海市\"
		},
		{
			\"provinceId\":\"31\",
			\"cityId\":\"31\",
			\"cityName\":\"上海\",
			\"fixName\":\"沪B\",
			\"frameLength\":\"0\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"上海市\"
		},
		{
			\"provinceId\":\"31\",
			\"cityId\":\"31\",
			\"cityName\":\"远效区\",
			\"fixName\":\"沪C\",
			\"frameLength\":\"0\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"上海\"
		},
		{
			\"provinceId\":\"31\",
			\"cityId\":\"31\",
			\"cityName\":\"上海\",
			\"fixName\":\"沪D\",
			\"frameLength\":\"0\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"上海市\"
		},
		{
			\"provinceId\":\"31\",
			\"cityId\":\"31\",
			\"cityName\":\"上海\",
			\"fixName\":\"沪E\",
			\"frameLength\":\"0\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"上海市\"
		},
		{
			\"provinceId\":\"31\",
			\"cityId\":\"31\",
			\"cityName\":\"上海\",
			\"fixName\":\"沪F\",
			\"frameLength\":\"0\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"上海市\"
		},
		{
			\"provinceId\":\"31\",
			\"cityId\":\"31\",
			\"cityName\":\"上海\",
			\"fixName\":\"沪G\",
			\"frameLength\":\"0\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"上海市\"
		},
		{
			\"provinceId\":\"31\",
			\"cityId\":\"31\",
			\"cityName\":\"上海\",
			\"fixName\":\"沪H\",
			\"frameLength\":\"0\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"上海市\"
		},
		{
			\"provinceId\":\"31\",
			\"cityId\":\"31\",
			\"cityName\":\"上海\",
			\"fixName\":\"沪F\",
			\"frameLength\":\"0\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"上海市\"
		},
		{
			\"provinceId\":\"31\",
			\"cityId\":\"31\",
			\"cityName\":\"上海\",
			\"fixName\":\"沪J\",
			\"frameLength\":\"0\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"上海市\"
		},
		{
			\"provinceId\":\"31\",
			\"cityId\":\"31\",
			\"cityName\":\"上海\",
			\"fixName\":\"沪M\",
			\"frameLength\":\"0\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"上海市\"
		},
		{
			\"provinceId\":\"31\",
			\"cityId\":\"31\",
			\"cityName\":\"上海\",
			\"fixName\":\"沪K\",
			\"frameLength\":\"0\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"上海市\"
		},
		{
			\"provinceId\":\"31\",
			\"cityId\":\"31\",
			\"cityName\":\"上海\",
			\"fixName\":\"沪L\",
			\"frameLength\":\"0\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"上海市\"
		},
		{
			\"provinceId\":\"32\",
			\"cityId\":\"3201\",
			\"cityName\":\"南京\",
			\"fixName\":\"苏A\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江苏省\"
		},
		{
			\"provinceId\":\"32\",
			\"cityId\":\"3202\",
			\"cityName\":\"无锡\",
			\"fixName\":\"苏B\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江苏省\"
		},
		{
			\"provinceId\":\"32\",
			\"cityId\":\"3203\",
			\"cityName\":\"徐州\",
			\"fixName\":\"苏C\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江苏省\"
		},
		{
			\"provinceId\":\"32\",
			\"cityId\":\"3204\",
			\"cityName\":\"常州\",
			\"fixName\":\"苏D\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江苏省\"
		},
		{
			\"provinceId\":\"32\",
			\"cityId\":\"3205\",
			\"cityName\":\"苏州\",
			\"fixName\":\"苏E\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江苏省\"
		},
		{
			\"provinceId\":\"32\",
			\"cityId\":\"3206\",
			\"cityName\":\"南通\",
			\"fixName\":\"苏F\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江苏省\"
		},
		{
			\"provinceId\":\"32\",
			\"cityId\":\"3207\",
			\"cityName\":\"连云港\",
			\"fixName\":\"苏G\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江苏省\"
		},
		{
			\"provinceId\":\"32\",
			\"cityId\":\"3208\",
			\"cityName\":\"淮安\",
			\"fixName\":\"苏H\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江苏省\"
		},
		{
			\"provinceId\":\"32\",
			\"cityId\":\"3209\",
			\"cityName\":\"盐城\",
			\"fixName\":\"苏J\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江苏省\"
		},
		{
			\"provinceId\":\"32\",
			\"cityId\":\"3210\",
			\"cityName\":\"扬州\",
			\"fixName\":\"苏K\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江苏省\"
		},
		{
			\"provinceId\":\"32\",
			\"cityId\":\"3211\",
			\"cityName\":\"镇江\",
			\"fixName\":\"苏L\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江苏省\"
		},
		{
			\"provinceId\":\"32\",
			\"cityId\":\"3212\",
			\"cityName\":\"泰州\",
			\"fixName\":\"苏M\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江苏省\"
		},
		{
			\"provinceId\":\"32\",
			\"cityId\":\"3213\",
			\"cityName\":\"宿迁\",
			\"fixName\":\"苏N\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江苏省\"
		},
		{
			\"provinceId\":\"33\",
			\"cityId\":\"3301\",
			\"cityName\":\"杭州\",
			\"fixName\":\"浙A\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"浙江省\"
		},
		{
			\"provinceId\":\"33\",
			\"cityId\":\"3302\",
			\"cityName\":\"宁波\",
			\"fixName\":\"浙B\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"浙江省\"
		},
		{
			\"provinceId\":\"33\",
			\"cityId\":\"3303\",
			\"cityName\":\"温州\",
			\"fixName\":\"浙C\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"浙江省\"
		},
		{
			\"provinceId\":\"33\",
			\"cityId\":\"3304\",
			\"cityName\":\"嘉兴\",
			\"fixName\":\"浙F\",
			\"frameLength\":\"99\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"浙江省\"
		},
		{
			\"provinceId\":\"33\",
			\"cityId\":\"3305\",
			\"cityName\":\"湖州\",
			\"fixName\":\"浙E\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"浙江省\"
		},
		{
			\"provinceId\":\"33\",
			\"cityId\":\"3306\",
			\"cityName\":\"绍兴\",
			\"fixName\":\"浙D\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"浙江省\"
		},
		{
			\"provinceId\":\"33\",
			\"cityId\":\"3307\",
			\"cityName\":\"金华\",
			\"fixName\":\"浙G\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"浙江省\"
		},
		{
			\"provinceId\":\"33\",
			\"cityId\":\"3308\",
			\"cityName\":\"衢州\",
			\"fixName\":\"浙H\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"浙江省\"
		},
		{
			\"provinceId\":\"33\",
			\"cityId\":\"3309\",
			\"cityName\":\"舟山\",
			\"fixName\":\"浙L\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"浙江省\"
		},
		{
			\"provinceId\":\"33\",
			\"cityId\":\"3310\",
			\"cityName\":\"台州\",
			\"fixName\":\"浙J\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"浙江省\"
		},
		{
			\"provinceId\":\"33\",
			\"cityId\":\"3311\",
			\"cityName\":\"丽水\",
			\"fixName\":\"浙K\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"浙江省\"
		},
		{
			\"provinceId\":\"34\",
			\"cityId\":\"3401\",
			\"cityName\":\"合肥\",
			\"fixName\":\"皖A\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"安徽省\"
		},
		{
			\"provinceId\":\"34\",
			\"cityId\":\"3402\",
			\"cityName\":\"芜湖\",
			\"fixName\":\"皖B\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"安徽省\"
		},
		{
			\"provinceId\":\"34\",
			\"cityId\":\"3403\",
			\"cityName\":\"蚌埠\",
			\"fixName\":\"皖C\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"安徽省\"
		},
		{
			\"provinceId\":\"34\",
			\"cityId\":\"3404\",
			\"cityName\":\"淮南\",
			\"fixName\":\"皖D\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"安徽省\"
		},
		{
			\"provinceId\":\"34\",
			\"cityId\":\"3405\",
			\"cityName\":\"马鞍山\",
			\"fixName\":\"皖E\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"安徽省\"
		},
		{
			\"provinceId\":\"34\",
			\"cityId\":\"3406\",
			\"cityName\":\"淮北\",
			\"fixName\":\"皖F\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"安徽省\"
		},
		{
			\"provinceId\":\"34\",
			\"cityId\":\"3407\",
			\"cityName\":\"铜陵\",
			\"fixName\":\"皖G\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"安徽省\"
		},
		{
			\"provinceId\":\"34\",
			\"cityId\":\"3408\",
			\"cityName\":\"安庆\",
			\"fixName\":\"皖H\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"安徽省\"
		},
		{
			\"provinceId\":\"34\",
			\"cityId\":\"3410\",
			\"cityName\":\"黄山\",
			\"fixName\":\"皖J\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"安徽省\"
		},
		{
			\"provinceId\":\"34\",
			\"cityId\":\"3411\",
			\"cityName\":\"滁州\",
			\"fixName\":\"皖M\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"安徽省\"
		},
		{
			\"provinceId\":\"34\",
			\"cityId\":\"3412\",
			\"cityName\":\"阜阳\",
			\"fixName\":\"皖K\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"安徽省\"
		},
		{
			\"provinceId\":\"34\",
			\"cityId\":\"3413\",
			\"cityName\":\"宿州\",
			\"fixName\":\"皖L\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"安徽省\"
		},
		{
			\"provinceId\":\"34\",
			\"cityId\":\"3415\",
			\"cityName\":\"六安\",
			\"fixName\":\"皖N\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"安徽省\"
		},
		{
			\"provinceId\":\"34\",
			\"cityId\":\"3416\",
			\"cityName\":\"亳州\",
			\"fixName\":\"皖S\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"安徽省\"
		},
		{
			\"provinceId\":\"34\",
			\"cityId\":\"3417\",
			\"cityName\":\"池州\",
			\"fixName\":\"皖R\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"安徽省\"
		},
		{
			\"provinceId\":\"34\",
			\"cityId\":\"3418\",
			\"cityName\":\"宣城\",
			\"fixName\":\"皖P\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"安徽省\"
		},
		{
			\"provinceId\":\"34\",
			\"cityId\":\"340181\",
			\"cityName\":\"巢湖\",
			\"fixName\":\"皖Q\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"安徽省\"
		},
		{
			\"provinceId\":\"35\",
			\"cityId\":\"3501\",
			\"cityName\":\"福州\",
			\"fixName\":\"闽A\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"福建省\"
		},
		{
			\"provinceId\":\"35\",
			\"cityId\":\"3502\",
			\"cityName\":\"厦门\",
			\"fixName\":\"闽D\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"福建省\"
		},
		{
			\"provinceId\":\"35\",
			\"cityId\":\"3503\",
			\"cityName\":\"莆田\",
			\"fixName\":\"闽B\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"福建省\"
		},
		{
			\"provinceId\":\"35\",
			\"cityId\":\"3504\",
			\"cityName\":\"三明\",
			\"fixName\":\"闽G\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"福建省\"
		},
		{
			\"provinceId\":\"35\",
			\"cityId\":\"3505\",
			\"cityName\":\"泉州\",
			\"fixName\":\"闽C\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"福建省\"
		},
		{
			\"provinceId\":\"35\",
			\"cityId\":\"3506\",
			\"cityName\":\"漳州\",
			\"fixName\":\"闽E\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"福建省\"
		},
		{
			\"provinceId\":\"35\",
			\"cityId\":\"3507\",
			\"cityName\":\"南平\",
			\"fixName\":\"闽H\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"福建省\"
		},
		{
			\"provinceId\":\"35\",
			\"cityId\":\"3508\",
			\"cityName\":\"龙岩\",
			\"fixName\":\"闽F\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"福建省\"
		},
		{
			\"provinceId\":\"35\",
			\"cityId\":\"3509\",
			\"cityName\":\"宁德\",
			\"fixName\":\"闽J\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"福建省\"
		},
		{
			\"provinceId\":\"35\",
			\"cityId\":\"3510\",
			\"cityName\":\"省直系统\",
			\"fixName\":\"闽K\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"福建省\"
		},
		{
			\"provinceId\":\"36\",
			\"cityId\":\"3601\",
			\"cityName\":\"南昌\",
			\"fixName\":\"赣A\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江西省\"
		},
		{
			\"provinceId\":\"36\",
			\"cityId\":\"3602\",
			\"cityName\":\"景德镇\",
			\"fixName\":\"赣H\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江西省\"
		},
		{
			\"provinceId\":\"36\",
			\"cityId\":\"3603\",
			\"cityName\":\"萍乡\",
			\"fixName\":\"赣J\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江西省\"
		},
		{
			\"provinceId\":\"36\",
			\"cityId\":\"3604\",
			\"cityName\":\"九江\",
			\"fixName\":\"赣G\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江西省\"
		},
		{
			\"provinceId\":\"36\",
			\"cityId\":\"3605\",
			\"cityName\":\"新余\",
			\"fixName\":\"赣K\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江西省\"
		},
		{
			\"provinceId\":\"36\",
			\"cityId\":\"3606\",
			\"cityName\":\"鹰潭\",
			\"fixName\":\"赣L\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江西省\"
		},
		{
			\"provinceId\":\"36\",
			\"cityId\":\"3607\",
			\"cityName\":\"赣州\",
			\"fixName\":\"赣B\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江西省\"
		},
		{
			\"provinceId\":\"36\",
			\"cityId\":\"3608\",
			\"cityName\":\"吉安\",
			\"fixName\":\"赣D\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江西省\"
		},
		{
			\"provinceId\":\"36\",
			\"cityId\":\"3609\",
			\"cityName\":\"宜春\",
			\"fixName\":\"赣C\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江西省\"
		},
		{
			\"provinceId\":\"36\",
			\"cityId\":\"3610\",
			\"cityName\":\"抚州\",
			\"fixName\":\"赣F\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江西省\"
		},
		{
			\"provinceId\":\"36\",
			\"cityId\":\"3611\",
			\"cityName\":\"上饶\",
			\"fixName\":\"赣E\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江西省\"
		},
		{
			\"provinceId\":\"36\",
			\"cityId\":\"3612\",
			\"cityName\":\"南昌市,省直系统\",
			\"fixName\":\"赣M\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"江西省\"
		},
		{
			\"provinceId\":\"37\",
			\"cityId\":\"3701\",
			\"cityName\":\"济南\",
			\"fixName\":\"鲁A\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山东省\"
		},
		{
			\"provinceId\":\"37\",
			\"cityId\":\"3702\",
			\"cityName\":\"青岛\",
			\"fixName\":\"鲁B\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山东省\"
		},
		{
			\"provinceId\":\"37\",
			\"cityId\":\"3703\",
			\"cityName\":\"淄博\",
			\"fixName\":\"鲁C\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山东省\"
		},
		{
			\"provinceId\":\"37\",
			\"cityId\":\"3704\",
			\"cityName\":\"枣庄\",
			\"fixName\":\"鲁D\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山东省\"
		},
		{
			\"provinceId\":\"37\",
			\"cityId\":\"3705\",
			\"cityName\":\"东营\",
			\"fixName\":\"鲁E\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山东省\"
		},
		{
			\"provinceId\":\"37\",
			\"cityId\":\"3706\",
			\"cityName\":\"烟台\",
			\"fixName\":\"鲁F\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山东省\"
		},
		{
			\"provinceId\":\"37\",
			\"cityId\":\"3707\",
			\"cityName\":\"潍坊\",
			\"fixName\":\"鲁G\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山东省\"
		},
		{
			\"provinceId\":\"37\",
			\"cityId\":\"3708\",
			\"cityName\":\"济宁\",
			\"fixName\":\"鲁H\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山东省\"
		},
		{
			\"provinceId\":\"37\",
			\"cityId\":\"3709\",
			\"cityName\":\"泰安\",
			\"fixName\":\"鲁J\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山东省\"
		},
		{
			\"provinceId\":\"37\",
			\"cityId\":\"3710\",
			\"cityName\":\"威海\",
			\"fixName\":\"鲁K\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山东省\"
		},
		{
			\"provinceId\":\"37\",
			\"cityId\":\"3711\",
			\"cityName\":\"日照\",
			\"fixName\":\"鲁L\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山东省\"
		},
		{
			\"provinceId\":\"37\",
			\"cityId\":\"3712\",
			\"cityName\":\"莱芜\",
			\"fixName\":\"鲁S\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山东省\"
		},
		{
			\"provinceId\":\"37\",
			\"cityId\":\"3713\",
			\"cityName\":\"临沂\",
			\"fixName\":\"鲁Q\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山东省\"
		},
		{
			\"provinceId\":\"37\",
			\"cityId\":\"3714\",
			\"cityName\":\"德州\",
			\"fixName\":\"鲁N\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山东省\"
		},
		{
			\"provinceId\":\"37\",
			\"cityId\":\"3715\",
			\"cityName\":\"聊城\",
			\"fixName\":\"鲁P\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山东省\"
		},
		{
			\"provinceId\":\"37\",
			\"cityId\":\"3716\",
			\"cityName\":\"滨州\",
			\"fixName\":\"鲁M\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山东省\"
		},
		{
			\"provinceId\":\"37\",
			\"cityId\":\"3717\",
			\"cityName\":\"菏泽\",
			\"fixName\":\"鲁R\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山东省\"
		},
		{
			\"provinceId\":\"37\",
			\"cityId\":\"3718\",
			\"cityName\":\"青岛市增补\",
			\"fixName\":\"鲁U\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山东省\"
		},
		{
			\"provinceId\":\"37\",
			\"cityId\":\"3719\",
			\"cityName\":\"潍坊市增补\",
			\"fixName\":\"鲁V\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山东省\"
		},
		{
			\"provinceId\":\"37\",
			\"cityId\":\"3720\",
			\"cityName\":\"烟台市增补\",
			\"fixName\":\"鲁Y\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"山东省\"
		},
		{
			\"provinceId\":\"41\",
			\"cityId\":\"4101\",
			\"cityName\":\"郑州\",
			\"fixName\":\"豫A\",
			\"frameLength\":\"99\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"河南省\"
		},
		{
			\"provinceId\":\"41\",
			\"cityId\":\"4102\",
			\"cityName\":\"开封\",
			\"fixName\":\"豫B\",
			\"frameLength\":\"99\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"河南省\"
		},
		{
			\"provinceId\":\"41\",
			\"cityId\":\"4103\",
			\"cityName\":\"洛阳\",
			\"fixName\":\"豫C\",
			\"frameLength\":\"99\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"河南省\"
		},
		{
			\"provinceId\":\"41\",
			\"cityId\":\"4104\",
			\"cityName\":\"平顶山\",
			\"fixName\":\"豫D\",
			\"frameLength\":\"99\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"河南省\"
		},
		{
			\"provinceId\":\"41\",
			\"cityId\":\"4105\",
			\"cityName\":\"安阳\",
			\"fixName\":\"豫E\",
			\"frameLength\":\"99\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"河南省\"
		},
		{
			\"provinceId\":\"41\",
			\"cityId\":\"4106\",
			\"cityName\":\"鹤壁\",
			\"fixName\":\"豫F\",
			\"frameLength\":\"99\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"河南省\"
		},
		{
			\"provinceId\":\"41\",
			\"cityId\":\"4107\",
			\"cityName\":\"新乡\",
			\"fixName\":\"豫G\",
			\"frameLength\":\"99\",
			\"engineLength\":\"99\",
			\"canQuery\":false,
			\"provinceName\":\"河南省\"
		},
		{
			\"provinceId\":\"41\",
			\"cityId\":\"4108\",
			\"cityName\":\"焦作\",
			\"fixName\":\"豫H\",
			\"frameLength\":\"99\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"河南省\"
		},
		{
			\"provinceId\":\"41\",
			\"cityId\":\"4109\",
			\"cityName\":\"濮阳\",
			\"fixName\":\"豫J\",
			\"frameLength\":\"99\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"河南省\"
		},
		{
			\"provinceId\":\"41\",
			\"cityId\":\"4110\",
			\"cityName\":\"许昌\",
			\"fixName\":\"豫K\",
			\"frameLength\":\"99\",
			\"engineLength\":\"99\",
			\"canQuery\":false,
			\"provinceName\":\"河南省\"
		},
		{
			\"provinceId\":\"41\",
			\"cityId\":\"4111\",
			\"cityName\":\"漯河\",
			\"fixName\":\"豫L\",
			\"frameLength\":\"99\",
			\"engineLength\":\"99\",
			\"canQuery\":false,
			\"provinceName\":\"河南省\"
		},
		{
			\"provinceId\":\"41\",
			\"cityId\":\"4112\",
			\"cityName\":\"三门峡\",
			\"fixName\":\"豫M\",
			\"frameLength\":\"99\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"河南省\"
		},
		{
			\"provinceId\":\"41\",
			\"cityId\":\"4113\",
			\"cityName\":\"南阳\",
			\"fixName\":\"豫R\",
			\"frameLength\":\"99\",
			\"engineLength\":\"99\",
			\"canQuery\":false,
			\"provinceName\":\"河南省\"
		},
		{
			\"provinceId\":\"41\",
			\"cityId\":\"4114\",
			\"cityName\":\"商丘\",
			\"fixName\":\"豫N\",
			\"frameLength\":\"99\",
			\"engineLength\":\"99\",
			\"canQuery\":false,
			\"provinceName\":\"河南省\"
		},
		{
			\"provinceId\":\"41\",
			\"cityId\":\"4115\",
			\"cityName\":\"信阳\",
			\"fixName\":\"豫S\",
			\"frameLength\":\"99\",
			\"engineLength\":\"99\",
			\"canQuery\":false,
			\"provinceName\":\"河南省\"
		},
		{
			\"provinceId\":\"41\",
			\"cityId\":\"4116\",
			\"cityName\":\"周口\",
			\"fixName\":\"豫P\",
			\"frameLength\":\"99\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"河南省\"
		},
		{
			\"provinceId\":\"41\",
			\"cityId\":\"4117\",
			\"cityName\":\"驻马店\",
			\"fixName\":\"豫Q\",
			\"frameLength\":\"99\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"河南省\"
		},
		{
			\"provinceId\":\"41\",
			\"cityId\":\"419001\",
			\"cityName\":\"济源\",
			\"fixName\":\"豫U\",
			\"frameLength\":\"99\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"河南省\"
		},
		{
			\"provinceId\":\"42\",
			\"cityId\":\"4201\",
			\"cityName\":\"武汉\",
			\"fixName\":\"鄂A\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖北省\"
		},
		{
			\"provinceId\":\"42\",
			\"cityId\":\"4202\",
			\"cityName\":\"黄石\",
			\"fixName\":\"鄂B\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖北省\"
		},
		{
			\"provinceId\":\"42\",
			\"cityId\":\"4203\",
			\"cityName\":\"十堰\",
			\"fixName\":\"鄂C\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖北省\"
		},
		{
			\"provinceId\":\"42\",
			\"cityId\":\"4205\",
			\"cityName\":\"宜昌\",
			\"fixName\":\"鄂E\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖北省\"
		},
		{
			\"provinceId\":\"42\",
			\"cityId\":\"4206\",
			\"cityName\":\"襄阳\",
			\"fixName\":\"鄂F\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖北省\"
		},
		{
			\"provinceId\":\"42\",
			\"cityId\":\"4207\",
			\"cityName\":\"鄂州\",
			\"fixName\":\"鄂G\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖北省\"
		},
		{
			\"provinceId\":\"42\",
			\"cityId\":\"4208\",
			\"cityName\":\"荆门\",
			\"fixName\":\"鄂H\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖北省\"
		},
		{
			\"provinceId\":\"42\",
			\"cityId\":\"4209\",
			\"cityName\":\"孝感\",
			\"fixName\":\"鄂K\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖北省\"
		},
		{
			\"provinceId\":\"42\",
			\"cityId\":\"4210\",
			\"cityName\":\"荆州\",
			\"fixName\":\"鄂D\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖北省\"
		},
		{
			\"provinceId\":\"42\",
			\"cityId\":\"4211\",
			\"cityName\":\"黄冈\",
			\"fixName\":\"鄂J\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖北省\"
		},
		{
			\"provinceId\":\"42\",
			\"cityId\":\"4212\",
			\"cityName\":\"咸宁\",
			\"fixName\":\"鄂L\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖北省\"
		},
		{
			\"provinceId\":\"42\",
			\"cityId\":\"4213\",
			\"cityName\":\"随州\",
			\"fixName\":\"鄂S\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖北省\"
		},
		{
			\"provinceId\":\"42\",
			\"cityId\":\"4228\",
			\"cityName\":\"恩施土家族苗族自治州\",
			\"fixName\":\"鄂Q\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖北省\"
		},
		{
			\"provinceId\":\"42\",
			\"cityId\":\"429004\",
			\"cityName\":\"仙桃\",
			\"fixName\":\"鄂M\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖北省\"
		},
		{
			\"provinceId\":\"42\",
			\"cityId\":\"429005\",
			\"cityName\":\"潜江\",
			\"fixName\":\"鄂N\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖北省\"
		},
		{
			\"provinceId\":\"42\",
			\"cityId\":\"429006\",
			\"cityName\":\"天门\",
			\"fixName\":\"鄂R\",
			\"frameLength\":\"5\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"湖北省\"
		},
		{
			\"provinceId\":\"42\",
			\"cityId\":\"429021\",
			\"cityName\":\"神农架林区\",
			\"fixName\":\"鄂P\",
			\"frameLength\":\"5\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"湖北省\"
		},
		{
			\"provinceId\":\"43\",
			\"cityId\":\"4301\",
			\"cityName\":\"长沙\",
			\"fixName\":\"湘A\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖南省\"
		},
		{
			\"provinceId\":\"43\",
			\"cityId\":\"4302\",
			\"cityName\":\"株洲\",
			\"fixName\":\"湘B\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖南省\"
		},
		{
			\"provinceId\":\"43\",
			\"cityId\":\"4303\",
			\"cityName\":\"湘潭\",
			\"fixName\":\"湘C\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖南省\"
		},
		{
			\"provinceId\":\"43\",
			\"cityId\":\"4304\",
			\"cityName\":\"衡阳\",
			\"fixName\":\"湘D\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖南省\"
		},
		{
			\"provinceId\":\"43\",
			\"cityId\":\"4305\",
			\"cityName\":\"邵阳\",
			\"fixName\":\"湘E\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖南省\"
		},
		{
			\"provinceId\":\"43\",
			\"cityId\":\"4306\",
			\"cityName\":\"岳阳\",
			\"fixName\":\"湘F\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖南省\"
		},
		{
			\"provinceId\":\"43\",
			\"cityId\":\"4307\",
			\"cityName\":\"常德\",
			\"fixName\":\"湘J\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖南省\"
		},
		{
			\"provinceId\":\"43\",
			\"cityId\":\"4308\",
			\"cityName\":\"张家界\",
			\"fixName\":\"湘G\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖南省\"
		},
		{
			\"provinceId\":\"43\",
			\"cityId\":\"4309\",
			\"cityName\":\" 益阳 \",
			\"fixName\":\"湘H\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖南省\"
		},
		{
			\"provinceId\":\"43\",
			\"cityId\":\"4310\",
			\"cityName\":\"郴州\",
			\"fixName\":\"湘L\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖南省\"
		},
		{
			\"provinceId\":\"43\",
			\"cityId\":\"4311\",
			\"cityName\":\"永州\",
			\"fixName\":\"湘M\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖南省\"
		},
		{
			\"provinceId\":\"43\",
			\"cityId\":\"4312\",
			\"cityName\":\"怀化\",
			\"fixName\":\"湘N\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖南省\"
		},
		{
			\"provinceId\":\"43\",
			\"cityId\":\"4313\",
			\"cityName\":\"娄底\",
			\"fixName\":\"湘K\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖南省\"
		},
		{
			\"provinceId\":\"43\",
			\"cityId\":\"4331\",
			\"cityName\":\"湘西土家族苗族自治州\",
			\"fixName\":\"湘U\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"湖南省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"4401\",
			\"cityName\":\"广州\",
			\"fixName\":\"粤A\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"广东省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"4402\",
			\"cityName\":\"韶关\",
			\"fixName\":\"粤F\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"广东省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"4403\",
			\"cityName\":\"深圳\",
			\"fixName\":\"粤B\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"广东省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"4404\",
			\"cityName\":\"珠海\",
			\"fixName\":\"粤C\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"广东省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"4405\",
			\"cityName\":\"汕头\",
			\"fixName\":\"粤D\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"广东省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"4406\",
			\"cityName\":\"佛山\",
			\"fixName\":\"粤E\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"广东省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"4407\",
			\"cityName\":\"江门\",
			\"fixName\":\"粤J\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"广东省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"4408\",
			\"cityName\":\"湛江\",
			\"fixName\":\"粤G\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"广东省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"4409\",
			\"cityName\":\"茂名\",
			\"fixName\":\"粤K\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"广东省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"4412\",
			\"cityName\":\"肇庆\",
			\"fixName\":\"粤H\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"广东省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"4413\",
			\"cityName\":\"惠州\",
			\"fixName\":\"粤L\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"广东省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"4414\",
			\"cityName\":\"梅州\",
			\"fixName\":\"粤M\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"广东省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"4415\",
			\"cityName\":\"汕尾\",
			\"fixName\":\"粤N\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"广东省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"4416\",
			\"cityName\":\"河源\",
			\"fixName\":\"粤P\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"广东省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"4417\",
			\"cityName\":\"阳江\",
			\"fixName\":\"粤Q\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"广东省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"4418\",
			\"cityName\":\"清远\",
			\"fixName\":\"粤R\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"广东省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"4419\",
			\"cityName\":\"东莞\",
			\"fixName\":\"粤S\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"广东省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"4420\",
			\"cityName\":\"中山\",
			\"fixName\":\"粤T\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"广东省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"4451\",
			\"cityName\":\"潮州\",
			\"fixName\":\"粤U\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"广东省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"4452\",
			\"cityName\":\"揭阳\",
			\"fixName\":\"粤V\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"广东省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"4453\",
			\"cityName\":\"云浮\",
			\"fixName\":\"粤W\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"广东省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"440606\",
			\"cityName\":\"顺德\",
			\"fixName\":\"粤X\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"广东省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"440605\",
			\"cityName\":\"南海\",
			\"fixName\":\"粤Y\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"广东省\"
		},
		{
			\"provinceId\":\"44\",
			\"cityId\":\"4481\",
			\"cityName\":\"港澳入境\",
			\"fixName\":\"粤Z\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"港澳\"
		},
		{
			\"provinceId\":\"45\",
			\"cityId\":\"4501\",
			\"cityName\":\"南宁\",
			\"fixName\":\"桂A\",
			\"canQuery\":false,
			\"provinceName\":\"广西省\"
		},
		{
			\"provinceId\":\"45\",
			\"cityId\":\"4502\",
			\"cityName\":\"柳州\",
			\"fixName\":\"桂B\",
			\"canQuery\":false,
			\"provinceName\":\"广西省\"
		},
		{
			\"provinceId\":\"45\",
			\"cityId\":\"4503\",
			\"cityName\":\"桂林\",
			\"fixName\":\"桂C\",
			\"canQuery\":false,
			\"provinceName\":\"广西省\"
		},
		{
			\"provinceId\":\"45\",
			\"cityId\":\"4504\",
			\"cityName\":\"梧州\",
			\"fixName\":\"桂D\",
			\"canQuery\":false,
			\"provinceName\":\"广西省\"
		},
		{
			\"provinceId\":\"45\",
			\"cityId\":\"4505\",
			\"cityName\":\"北海\",
			\"fixName\":\"桂E\",
			\"canQuery\":false,
			\"provinceName\":\"广西省\"
		},
		{
			\"provinceId\":\"45\",
			\"cityId\":\"4506\",
			\"cityName\":\"防城港\",
			\"fixName\":\"桂P\",
			\"canQuery\":false,
			\"provinceName\":\"广西省\"
		},
		{
			\"provinceId\":\"45\",
			\"cityId\":\"4507\",
			\"cityName\":\"钦州\",
			\"fixName\":\"桂N\",
			\"canQuery\":false,
			\"provinceName\":\"广西省\"
		},
		{
			\"provinceId\":\"45\",
			\"cityId\":\"4508\",
			\"cityName\":\"贵港\",
			\"fixName\":\"桂R\",
			\"canQuery\":false,
			\"provinceName\":\"广西省\"
		},
		{
			\"provinceId\":\"45\",
			\"cityId\":\"4509\",
			\"cityName\":\"玉林\",
			\"fixName\":\"桂K\",
			\"canQuery\":false,
			\"provinceName\":\"广西省\"
		},
		{
			\"provinceId\":\"45\",
			\"cityId\":\"4510\",
			\"cityName\":\"百色\",
			\"fixName\":\"桂L\",
			\"canQuery\":false,
			\"provinceName\":\"广西省\"
		},
		{
			\"provinceId\":\"45\",
			\"cityId\":\"4511\",
			\"cityName\":\"贺州\",
			\"fixName\":\"桂J\",
			\"canQuery\":false,
			\"provinceName\":\"广西省\"
		},
		{
			\"provinceId\":\"45\",
			\"cityId\":\"4512\",
			\"cityName\":\"河池\",
			\"fixName\":\"桂M\",
			\"canQuery\":false,
			\"provinceName\":\"广西省\"
		},
		{
			\"provinceId\":\"45\",
			\"cityId\":\"4513\",
			\"cityName\":\"来宾\",
			\"fixName\":\"桂G\",
			\"canQuery\":false,
			\"provinceName\":\"广西省\"
		},
		{
			\"provinceId\":\"45\",
			\"cityId\":\"4514\",
			\"cityName\":\"崇左\",
			\"fixName\":\"桂F\",
			\"canQuery\":false,
			\"provinceName\":\"广西省\"
		},
		{
			\"provinceId\":\"45\",
			\"cityId\":\"4525\",
			\"cityName\":\"桂林地区\",
			\"fixName\":\"桂H\",
			\"canQuery\":false,
			\"provinceName\":\"广西省\"
		},
		{
			\"provinceId\":\"46\",
			\"cityId\":\"4601\",
			\"cityName\":\"海口\",
			\"fixName\":\"琼A\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"海南省\"
		},
		{
			\"provinceId\":\"46\",
			\"cityId\":\"4602\",
			\"cityName\":\"三亚\",
			\"fixName\":\"琼B\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"海南省\"
		},
		{
			\"provinceId\":\"46\",
			\"cityId\":\"4606\",
			\"cityName\":\"洋浦开发区\",
			\"fixName\":\"琼E\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"海南省\"
		},
		{
			\"provinceId\":\"46\",
			\"cityId\":\"469001\",
			\"cityName\":\"五指山\",
			\"fixName\":\"琼D\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"海南省\"
		},
		{
			\"provinceId\":\"46\",
			\"cityId\":\"469002\",
			\"cityName\":\"琼海\",
			\"fixName\":\"琼C\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"海南省\"
		},
		{
			\"provinceId\":\"46\",
			\"cityId\":\"469003\",
			\"cityName\":\"儋州市\",
			\"fixName\":\"琼F\",
			\"frameLength\":\"6\",
			\"engineLength\":\"0\",
			\"canQuery\":true,
			\"provinceName\":\"海南省\"
		},
		{
			\"provinceId\":\"50\",
			\"cityId\":\"50\",
			\"cityName\":\"重庆\",
			\"fixName\":\"渝\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"重庆市\"
		},
		{
			\"provinceId\":\"51\",
			\"cityId\":\"5101\",
			\"cityName\":\"成都\",
			\"fixName\":\"川A\",
			\"frameLength\":\"8\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"四川省\"
		},
		{
			\"provinceId\":\"51\",
			\"cityId\":\"5103\",
			\"cityName\":\"自贡\",
			\"fixName\":\"川C\",
			\"frameLength\":\"8\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"四川省\"
		},
		{
			\"provinceId\":\"51\",
			\"cityId\":\"5104\",
			\"cityName\":\"攀枝花\",
			\"fixName\":\"川D\",
			\"frameLength\":\"8\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"四川省\"
		},
		{
			\"provinceId\":\"51\",
			\"cityId\":\"5105\",
			\"cityName\":\"泸州\",
			\"fixName\":\"川E\",
			\"frameLength\":\"8\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"四川省\"
		},
		{
			\"provinceId\":\"51\",
			\"cityId\":\"5106\",
			\"cityName\":\"德阳\",
			\"fixName\":\"川F\",
			\"frameLength\":\"8\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"四川省\"
		},
		{
			\"provinceId\":\"51\",
			\"cityId\":\"5107\",
			\"cityName\":\"绵阳\",
			\"fixName\":\"川B\",
			\"frameLength\":\"8\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"四川省\"
		},
		{
			\"provinceId\":\"51\",
			\"cityId\":\"5108\",
			\"cityName\":\"广元\",
			\"fixName\":\"川H\",
			\"frameLength\":\"8\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"四川省\"
		},
		{
			\"provinceId\":\"51\",
			\"cityId\":\"5109\",
			\"cityName\":\"遂宁\",
			\"fixName\":\"川J\",
			\"frameLength\":\"8\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"四川省\"
		},
		{
			\"provinceId\":\"51\",
			\"cityId\":\"5110\",
			\"cityName\":\"内江\",
			\"fixName\":\"川K\",
			\"frameLength\":\"8\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"四川省\"
		},
		{
			\"provinceId\":\"51\",
			\"cityId\":\"5111\",
			\"cityName\":\"乐山\",
			\"fixName\":\"川L\",
			\"frameLength\":\"8\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"四川省\"
		},
		{
			\"provinceId\":\"51\",
			\"cityId\":\"5113\",
			\"cityName\":\"南充\",
			\"fixName\":\"川R\",
			\"frameLength\":\"8\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"四川省\"
		},
		{
			\"provinceId\":\"51\",
			\"cityId\":\"5114\",
			\"cityName\":\"眉山\",
			\"fixName\":\"川Z\",
			\"frameLength\":\"8\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"四川省\"
		},
		{
			\"provinceId\":\"51\",
			\"cityId\":\"5115\",
			\"cityName\":\"宜宾\",
			\"fixName\":\"川Q\",
			\"frameLength\":\"8\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"四川省\"
		},
		{
			\"provinceId\":\"51\",
			\"cityId\":\"5116\",
			\"cityName\":\"广安\",
			\"fixName\":\"川X\",
			\"frameLength\":\"8\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"四川省\"
		},
		{
			\"provinceId\":\"51\",
			\"cityId\":\"5117\",
			\"cityName\":\"达州\",
			\"fixName\":\"川S\",
			\"frameLength\":\"8\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"四川省\"
		},
		{
			\"provinceId\":\"51\",
			\"cityId\":\"5118\",
			\"cityName\":\"雅安\",
			\"fixName\":\"川T\",
			\"frameLength\":\"8\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"四川省\"
		},
		{
			\"provinceId\":\"51\",
			\"cityId\":\"5119\",
			\"cityName\":\"巴中\",
			\"fixName\":\"川Y\",
			\"frameLength\":\"8\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"四川省\"
		},
		{
			\"provinceId\":\"51\",
			\"cityId\":\"5120\",
			\"cityName\":\"资阳\",
			\"fixName\":\"川M\",
			\"frameLength\":\"8\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"四川省\"
		},
		{
			\"provinceId\":\"51\",
			\"cityId\":\"5132\",
			\"cityName\":\"阿坝\",
			\"fixName\":\"川U\",
			\"frameLength\":\"8\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"四川省\"
		},
		{
			\"provinceId\":\"51\",
			\"cityId\":\"5133\",
			\"cityName\":\"甘孜\",
			\"fixName\":\"川V\",
			\"frameLength\":\"8\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"四川省\"
		},
		{
			\"provinceId\":\"51\",
			\"cityId\":\"5134\",
			\"cityName\":\"凉山彝族自治州\",
			\"fixName\":\"川W\",
			\"frameLength\":\"8\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"四川全省\"
		},
		{
			\"provinceId\":\"52\",
			\"cityId\":\"5201\",
			\"cityName\":\"贵阳\",
			\"fixName\":\"贵A\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"贵州省\"
		},
		{
			\"provinceId\":\"52\",
			\"cityId\":\"5202\",
			\"cityName\":\"六盘水\",
			\"fixName\":\"贵B\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"贵州省\"
		},
		{
			\"provinceId\":\"52\",
			\"cityId\":\"5203\",
			\"cityName\":\"遵义\",
			\"fixName\":\"贵C\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"贵州省\"
		},
		{
			\"provinceId\":\"52\",
			\"cityId\":\"5204\",
			\"cityName\":\"安顺\",
			\"fixName\":\"贵G\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"贵州省\"
		},
		{
			\"provinceId\":\"52\",
			\"cityId\":\"5205\",
			\"cityName\":\"毕节\",
			\"fixName\":\"贵F\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"贵州省\"
		},
		{
			\"provinceId\":\"52\",
			\"cityId\":\"5206\",
			\"cityName\":\"铜仁\",
			\"fixName\":\"贵D\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"贵州省\"
		},
		{
			\"provinceId\":\"52\",
			\"cityId\":\"5223\",
			\"cityName\":\"黔西南布依族苗族自治\",
			\"fixName\":\"贵E\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"贵州省\"
		},
		{
			\"provinceId\":\"52\",
			\"cityId\":\"5226\",
			\"cityName\":\"黔东南苗族侗族自治州\",
			\"fixName\":\"贵H\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"贵州省\"
		},
		{
			\"provinceId\":\"52\",
			\"cityId\":\"5227\",
			\"cityName\":\"黔南布依族苗族自治州\",
			\"fixName\":\"贵J\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"贵州省\"
		},
		{
			\"provinceId\":\"53\",
			\"cityId\":\"5301\",
			\"cityName\":\"昆明\",
			\"fixName\":\"云A\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"云南省\"
		},
		{
			\"provinceId\":\"53\",
			\"cityId\":\"5303\",
			\"cityName\":\"曲靖\",
			\"fixName\":\"云D\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"云南省\"
		},
		{
			\"provinceId\":\"53\",
			\"cityId\":\"5304\",
			\"cityName\":\"玉溪\",
			\"fixName\":\"云F\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"云南省\"
		},
		{
			\"provinceId\":\"53\",
			\"cityId\":\"5305\",
			\"cityName\":\"保山\",
			\"fixName\":\"云M\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"云南省\"
		},
		{
			\"provinceId\":\"53\",
			\"cityId\":\"5306\",
			\"cityName\":\"昭通\",
			\"fixName\":\"云C\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"云南省\"
		},
		{
			\"provinceId\":\"53\",
			\"cityId\":\"5307\",
			\"cityName\":\"丽江\",
			\"fixName\":\"云P\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"云南省\"
		},
		{
			\"provinceId\":\"53\",
			\"cityId\":\"5308\",
			\"cityName\":\"普洱\",
			\"fixName\":\"云J\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"云南省\"
		},
		{
			\"provinceId\":\"53\",
			\"cityId\":\"5309\",
			\"cityName\":\"临沧\",
			\"fixName\":\"云S\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"云南省\"
		},
		{
			\"provinceId\":\"53\",
			\"cityId\":\"5323\",
			\"cityName\":\"楚雄\",
			\"fixName\":\"云E\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"云南省\"
		},
		{
			\"provinceId\":\"53\",
			\"cityId\":\"5325\",
			\"cityName\":\"红河\",
			\"fixName\":\"云G\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"云南省\"
		},
		{
			\"provinceId\":\"53\",
			\"cityId\":\"5326\",
			\"cityName\":\"文山\",
			\"fixName\":\"云H\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"云南省\"
		},
		{
			\"provinceId\":\"53\",
			\"cityId\":\"5328\",
			\"cityName\":\"西双版纳\",
			\"fixName\":\"云K\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"云南省\"
		},
		{
			\"provinceId\":\"53\",
			\"cityId\":\"5329\",
			\"cityName\":\"大理\",
			\"fixName\":\"云L\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"云南省\"
		},
		{
			\"provinceId\":\"53\",
			\"cityId\":\"5331\",
			\"cityName\":\"德宏\",
			\"fixName\":\"云N\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"云南省\"
		},
		{
			\"provinceId\":\"53\",
			\"cityId\":\"5333\",
			\"cityName\":\"怒江\",
			\"fixName\":\"云Q\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"云南省\"
		},
		{
			\"provinceId\":\"53\",
			\"cityId\":\"5334\",
			\"cityName\":\"迪庆\",
			\"fixName\":\"云R\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"云南省\"
		},
		{
			\"provinceId\":\"54\",
			\"cityId\":\"5401\",
			\"cityName\":\"拉萨\",
			\"fixName\":\"藏A\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"西藏藏族自治州\"
		},
		{
			\"provinceId\":\"54\",
			\"cityId\":\"5421\",
			\"cityName\":\"昌都\",
			\"fixName\":\"藏B\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"西藏藏族自治州\"
		},
		{
			\"provinceId\":\"54\",
			\"cityId\":\"5422\",
			\"cityName\":\"山南\",
			\"fixName\":\"藏C\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"西藏藏族自治州\"
		},
		{
			\"provinceId\":\"54\",
			\"cityId\":\"5423\",
			\"cityName\":\"日喀则\",
			\"fixName\":\"藏D\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"西藏藏族自治州\"
		},
		{
			\"provinceId\":\"54\",
			\"cityId\":\"5424\",
			\"cityName\":\"那曲\",
			\"fixName\":\"藏E\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"西藏藏族自治州\"
		},
		{
			\"provinceId\":\"54\",
			\"cityId\":\"5425\",
			\"cityName\":\"阿里\",
			\"fixName\":\"藏F\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"西藏藏族自治州\"
		},
		{
			\"provinceId\":\"54\",
			\"cityId\":\"5426\",
			\"cityName\":\"林芝\",
			\"fixName\":\"藏G\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"西藏藏族自治州\"
		},
		{
			\"provinceId\":\"61\",
			\"cityId\":\"6101\",
			\"cityName\":\"西安\",
			\"fixName\":\"陕A\",
			\"frameLength\":\"6\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"陕西省\"
		},
		{
			\"provinceId\":\"61\",
			\"cityId\":\"6102\",
			\"cityName\":\"铜川\",
			\"fixName\":\"陕B\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"陕西省\"
		},
		{
			\"provinceId\":\"61\",
			\"cityId\":\"6103\",
			\"cityName\":\"宝鸡\",
			\"fixName\":\"陕C\",
			\"frameLength\":\"4\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"陕西省\"
		},
		{
			\"provinceId\":\"61\",
			\"cityId\":\"6104\",
			\"cityName\":\"咸阳\",
			\"fixName\":\"陕D\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"陕西省\"
		},
		{
			\"provinceId\":\"61\",
			\"cityId\":\"6105\",
			\"cityName\":\"渭南\",
			\"fixName\":\"陕E\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"陕西省\"
		},
		{
			\"provinceId\":\"61\",
			\"cityId\":\"6106\",
			\"cityName\":\"延安\",
			\"fixName\":\"陕J\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"陕西省\"
		},
		{
			\"provinceId\":\"61\",
			\"cityId\":\"6107\",
			\"cityName\":\"汉中\",
			\"fixName\":\"陕F\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"陕西省\"
		},
		{
			\"provinceId\":\"61\",
			\"cityId\":\"6108\",
			\"cityName\":\"榆林\",
			\"fixName\":\"陕K\",
			\"frameLength\":\"6\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"陕西省\"
		},
		{
			\"provinceId\":\"61\",
			\"cityId\":\"6109\",
			\"cityName\":\"安康\",
			\"fixName\":\"陕G\",
			\"frameLength\":\"6\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"陕西省\"
		},
		{
			\"provinceId\":\"61\",
			\"cityId\":\"6110\",
			\"cityName\":\"商洛\",
			\"fixName\":\"陕H\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"陕西省\"
		},
		{
			\"provinceId\":\"61\",
			\"cityId\":\"6125\",
			\"cityName\":\"杨凌\",
			\"fixName\":\"陕V\",
			\"frameLength\":\"6\",
			\"engineLength\":\"99\",
			\"canQuery\":true,
			\"provinceName\":\"陕西省\"
		},
		{
			\"provinceId\":\"62\",
			\"cityId\":\"6201\",
			\"cityName\":\"兰州\",
			\"fixName\":\"甘A\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":false,
			\"provinceName\":\"甘肃省\"
		},
		{
			\"provinceId\":\"62\",
			\"cityId\":\"6202\",
			\"cityName\":\"嘉峪关\",
			\"fixName\":\"甘B\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":false,
			\"provinceName\":\"甘肃省\"
		},
		{
			\"provinceId\":\"62\",
			\"cityId\":\"6203\",
			\"cityName\":\"金昌\",
			\"fixName\":\"甘C\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":false,
			\"provinceName\":\"甘肃省\"
		},
		{
			\"provinceId\":\"62\",
			\"cityId\":\"6204\",
			\"cityName\":\"白银\",
			\"fixName\":\"甘D\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":false,
			\"provinceName\":\"甘肃省\"
		},
		{
			\"provinceId\":\"62\",
			\"cityId\":\"6205\",
			\"cityName\":\"天水\",
			\"fixName\":\"甘E\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":false,
			\"provinceName\":\"甘肃省\"
		},
		{
			\"provinceId\":\"62\",
			\"cityId\":\"6206\",
			\"cityName\":\"武威\",
			\"fixName\":\"甘H\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":false,
			\"provinceName\":\"甘肃省\"
		},
		{
			\"provinceId\":\"62\",
			\"cityId\":\"6207\",
			\"cityName\":\"张掖\",
			\"fixName\":\"甘G\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":false,
			\"provinceName\":\"甘肃省\"
		},
		{
			\"provinceId\":\"62\",
			\"cityId\":\"6208\",
			\"cityName\":\"平凉\",
			\"fixName\":\"甘L\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":false,
			\"provinceName\":\"甘肃省\"
		},
		{
			\"provinceId\":\"62\",
			\"cityId\":\"6209\",
			\"cityName\":\"酒泉\",
			\"fixName\":\"甘F\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":false,
			\"provinceName\":\"甘肃省\"
		},
		{
			\"provinceId\":\"62\",
			\"cityId\":\"6210\",
			\"cityName\":\"庆阳\",
			\"fixName\":\"甘M\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":false,
			\"provinceName\":\"甘肃省\"
		},
		{
			\"provinceId\":\"62\",
			\"cityId\":\"6211\",
			\"cityName\":\"定西\",
			\"fixName\":\"甘J\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":false,
			\"provinceName\":\"甘肃省\"
		},
		{
			\"provinceId\":\"62\",
			\"cityId\":\"6212\",
			\"cityName\":\"陇南\",
			\"fixName\":\"甘K\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":false,
			\"provinceName\":\"甘肃省\"
		},
		{
			\"provinceId\":\"62\",
			\"cityId\":\"6229\",
			\"cityName\":\"临夏回族自治州\",
			\"fixName\":\"甘N\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":false,
			\"provinceName\":\"甘肃省\"
		},
		{
			\"provinceId\":\"62\",
			\"cityId\":\"6230\",
			\"cityName\":\"甘南藏族自治州\",
			\"fixName\":\"甘P\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":false,
			\"provinceName\":\"甘肃省\"
		},
		{
			\"provinceId\":\"63\",
			\"cityId\":\"6301\",
			\"cityName\":\"西宁\",
			\"fixName\":\"青A\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"青海省\"
		},
		{
			\"provinceId\":\"63\",
			\"cityId\":\"6321\",
			\"cityName\":\"海东地区\",
			\"fixName\":\"青B\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"青海省\"
		},
		{
			\"provinceId\":\"63\",
			\"cityId\":\"6322\",
			\"cityName\":\"海北藏族自治州\",
			\"fixName\":\"青C\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"青海省\"
		},
		{
			\"provinceId\":\"63\",
			\"cityId\":\"6323\",
			\"cityName\":\"黄南藏族自治州\",
			\"fixName\":\"青D\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"青海省\"
		},
		{
			\"provinceId\":\"63\",
			\"cityId\":\"6325\",
			\"cityName\":\"海南藏族自治州\",
			\"fixName\":\"青E\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"青海省\"
		},
		{
			\"provinceId\":\"63\",
			\"cityId\":\"6326\",
			\"cityName\":\"果洛藏族自治州\",
			\"fixName\":\"青F\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"青海省\"
		},
		{
			\"provinceId\":\"63\",
			\"cityId\":\"6327\",
			\"cityName\":\"玉树藏族自治州\",
			\"fixName\":\"青G\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"青海省\"
		},
		{
			\"provinceId\":\"63\",
			\"cityId\":\"6328\",
			\"cityName\":\"海西蒙古族藏族自治州\",
			\"fixName\":\"青H\",
			\"frameLength\":\"99\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"青海省\"
		},
		{
			\"provinceId\":\"64\",
			\"cityId\":\"6401\",
			\"cityName\":\"银川\",
			\"fixName\":\"宁A\",
			\"frameLength\":\"6\",
			\"engineLength\":\"4\",
			\"canQuery\":true,
			\"provinceName\":\"宁夏回族自治区\"
		},
		{
			\"provinceId\":\"64\",
			\"cityId\":\"6402\",
			\"cityName\":\"石嘴山\",
			\"fixName\":\"宁B\",
			\"frameLength\":\"6\",
			\"engineLength\":\"4\",
			\"canQuery\":true,
			\"provinceName\":\"宁夏回族自治区\"
		},
		{
			\"provinceId\":\"64\",
			\"cityId\":\"6403\",
			\"cityName\":\"吴忠\",
			\"fixName\":\"宁C\",
			\"frameLength\":\"6\",
			\"engineLength\":\"4\",
			\"canQuery\":true,
			\"provinceName\":\"宁夏回族自治区\"
		},
		{
			\"provinceId\":\"64\",
			\"cityId\":\"6404\",
			\"cityName\":\"固原\",
			\"fixName\":\"宁D\",
			\"frameLength\":\"6\",
			\"engineLength\":\"4\",
			\"canQuery\":true,
			\"provinceName\":\"宁夏回族自治区\"
		},
		{
			\"provinceId\":\"64\",
			\"cityId\":\"6405\",
			\"cityName\":\"中卫\",
			\"fixName\":\"宁E\",
			\"frameLength\":\"6\",
			\"engineLength\":\"4\",
			\"canQuery\":true,
			\"provinceName\":\"宁夏回族自治区\"
		},
		{
			\"provinceId\":\"65\",
			\"cityId\":\"6501\",
			\"cityName\":\"乌鲁木齐\",
			\"fixName\":\"新A\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"新疆维吾尔族自治区\"
		},
		{
			\"provinceId\":\"65\",
			\"cityId\":\"6502\",
			\"cityName\":\"克拉玛依\",
			\"fixName\":\"新J\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"新疆维吾尔族自治区\"
		},
		{
			\"provinceId\":\"65\",
			\"cityId\":\"6521\",
			\"cityName\":\"吐鲁番地区\",
			\"fixName\":\"新K\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"新疆维吾尔族自治区\"
		},
		{
			\"provinceId\":\"65\",
			\"cityId\":\"6522\",
			\"cityName\":\"哈密地区\",
			\"fixName\":\"新L\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"新疆维吾尔族自治区\"
		},
		{
			\"provinceId\":\"65\",
			\"cityId\":\"6523\",
			\"cityName\":\"昌吉回族自治州\",
			\"fixName\":\"新B\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"新疆维吾尔族自治区\"
		},
		{
			\"provinceId\":\"65\",
			\"cityId\":\"6527\",
			\"cityName\":\"博尔塔拉蒙古自治州\",
			\"fixName\":\"新E\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"新疆维吾尔族自治区\"
		},
		{
			\"provinceId\":\"65\",
			\"cityId\":\"6528\",
			\"cityName\":\"巴音郭楞蒙古自治州\",
			\"fixName\":\"新M\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"新疆维吾尔族自治区\"
		},
		{
			\"provinceId\":\"65\",
			\"cityId\":\"6529\",
			\"cityName\":\"阿克苏地区\",
			\"fixName\":\"新N\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"新疆维吾尔族自治区\"
		},
		{
			\"provinceId\":\"65\",
			\"cityId\":\"6530\",
			\"cityName\":\"克孜勒苏柯尔克孜自治\",
			\"fixName\":\"新P\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"新疆维吾尔族自治区\"
		},
		{
			\"provinceId\":\"65\",
			\"cityId\":\"6531\",
			\"cityName\":\"喀什地区\",
			\"fixName\":\"新Q\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"新疆维吾尔族自治区\"
		},
		{
			\"provinceId\":\"65\",
			\"cityId\":\"6532\",
			\"cityName\":\"和田地区\",
			\"fixName\":\"新R\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"新疆维吾尔族自治区\"
		},
		{
			\"provinceId\":\"65\",
			\"cityId\":\"6540\",
			\"cityName\":\"伊犁哈萨克自治州\",
			\"fixName\":\"新F\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"新疆维吾尔族自治区\"
		},
		{
			\"provinceId\":\"65\",
			\"cityId\":\"6542\",
			\"cityName\":\"塔城地区\",
			\"fixName\":\"新G\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"新疆维吾尔族自治区\"
		},
		{
			\"provinceId\":\"65\",
			\"cityId\":\"6543\",
			\"cityName\":\"阿勒泰地区\",
			\"fixName\":\"新H\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"新疆维吾尔族自治区\"
		},
		{
			\"provinceId\":\"65\",
			\"cityId\":\"654003\",
			\"cityName\":\"奎屯\",
			\"fixName\":\"新D\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"新疆维吾尔族自治区\"
		},
		{
			\"provinceId\":\"65\",
			\"cityId\":\"659001\",
			\"cityName\":\"石河子\",
			\"fixName\":\"新C\",
			\"frameLength\":\"6\",
			\"engineLength\":\"6\",
			\"canQuery\":true,
			\"provinceName\":\"新疆维吾尔族自治区\"
		}
	]
}";
        dump(count(json_decode($a,true)['result']));
    }
}